### ISSUE TITLE
.Rmd output args not respected

### ISSUE THREAD

**Issue by schloerke** [hafen/packagedocs#11]
I, apparently, have no clue how template arguments and output arguments work.

This is **very** frustrating.  I thought they were supplied to the function at run time. They are not.

Even in our example, we can not turn the `toc` off like they can in rmarkdown::html_document

ours (doesn't work):

``` yaml

---
title: "packagedocs Documentation"
output:
  packagedocs::packagedocs:
    toc: false

---
```

ours (works)

``` yaml

---
title: "packagedocs Documentation"
output: packagedocs::packagedocs:
toc: false

---
```

theirs (supposedly works):

``` yaml

---
title: "packagedocs Documentation"
output:
  rmarkdown::html_document:
    toc: false

---
```

This also applies to lazyrmd.  the args of `lazy_render_fn` and `lazy_render_package` are doing nothing.

@hafen ... how does the second layer args work?
